### ISSUE TITLE
Enhancements observed in workshops

### ISSUE THREAD

**Issue by David-Estevez** [UC3Music/drawdio#5]
These are several possible improvements for Drawdio observed during the development of workshops:

* [x] More spacing between resistor pads
* [x] Better polarity indication for IC
* [x] Larger holes for zip ties
* [x] Larger slot for copper strip
* [x] Location of C3 is ambiguous
* [x] Battery holder is very hard to insert in holes
* [x] Battery holder polarity is not indicated in silkscreen
* [x] Q1 silkscreen is hard to read (due to via hole)

**Comment by JorFru** [comment]
Todo resuelto en https://github.com/UC3Music/drawdio/commit/0b4b8f43eea45b36ef9ca76c592d2b332f47224a

**Comment by David-Estevez** [comment]
:clap: :clap: :clap:
